<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-23T10:32:15 IST" name="Default suite" finished-at="2025-08-23T10:32:31 IST" duration-ms="16292">
    <groups>
    </groups>
    <test started-at="2025-08-23T10:32:15 IST" name="Default test" finished-at="2025-08-23T10:32:31 IST" duration-ms="16292">
      <class name="com.hclTech.login.ProductTest">
        <test-method is-config="true" signature="launchBrowserAndLogin()[pri:0, instance:com.hclTech.login.ProductTest@1f2586d6]" started-at="2025-08-23T10:32:15 IST" name="launchBrowserAndLogin" finished-at="2025-08-23T10:32:27 IST" duration-ms="12193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserAndLogin -->
        <test-method signature="verifyAllProducts()[pri:1, instance:com.hclTech.login.ProductTest@1f2586d6]" started-at="2025-08-23T10:32:27 IST" name="verifyAllProducts" finished-at="2025-08-23T10:32:30 IST" duration-ms="2833" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Mismatch found for: Test.allTheThings() T-Shirt (Red)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Mismatch found for: Test.allTheThings() T-Shirt (Red)
at org.testng.Assert.fail(Assert.java:111)
at com.hclTech.login.ProductTest.verifyProduct(ProductTest.java:83)
at com.hclTech.login.ProductTest.verifyAllProducts(ProductTest.java:148)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAllProducts -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hclTech.login.ProductTest@1f2586d6]" started-at="2025-08-23T10:32:30 IST" name="tearDown" finished-at="2025-08-23T10:32:31 IST" duration-ms="1145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hclTech.login.ProductTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
